language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - export COMPOSER_MEMORY_LIMIT=-1
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

script:
  - composer test -- --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
